import PDFDocument from 'pdfkit';
import { uploadToR2 } from '../storage/r2.js';
import { logger } from '../../utils/logger.js';
import type { Itinerary, DayPlan } from '../../types/trip.js';

/**
 * Generate a shareable PDF of a trip itinerary.
 * Upload to R2 and return a public URL for WhatsApp sharing.
 */
export async function generateItineraryPdf(
  itinerary: Itinerary,
  tripTitle: string,
): Promise<string> {
  const buffer = await buildPdf(itinerary, tripTitle);
  const key = `itineraries/${Date.now()}_${tripTitle.replace(/\s+/g, '-').slice(0, 40)}.pdf`;

  const url = await uploadToR2(buffer, key, 'application/pdf');
  if (!url) {
    throw new Error('R2 not configured — cannot generate sharable PDF');
  }

  logger.info({ key, bytes: buffer.length }, 'Itinerary PDF uploaded to R2');
  return url;
}

function buildPdf(itinerary: Itinerary, title: string): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, size: 'A4' });
    const chunks: Buffer[] = [];

    doc.on('data', (chunk) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    // --- Cover / Title ---
    doc
      .fontSize(28)
      .font('Helvetica-Bold')
      .text(title, { align: 'center' });

    doc.moveDown(0.5);
    doc
      .fontSize(12)
      .font('Helvetica')
      .fillColor('#666666')
      .text(`Generated by Destinx · ${formatDate(new Date().toISOString())}`, { align: 'center' });

    if (itinerary.overview) {
      doc.moveDown(1);
      doc
        .fontSize(12)
        .fillColor('#333333')
        .font('Helvetica-Oblique')
        .text(itinerary.overview, { align: 'center' });
    }

    doc.moveDown(1);
    doc.moveTo(50, doc.y).lineTo(545, doc.y).strokeColor('#CCCCCC').stroke();
    doc.moveDown(1);

    // --- Day-by-day schedule ---
    for (const day of itinerary.days) {
      renderDay(doc, day);
    }

    // --- Packing tips ---
    if (itinerary.packing_tips && itinerary.packing_tips.length > 0) {
      doc.addPage();
      doc
        .fontSize(16)
        .font('Helvetica-Bold')
        .fillColor('#1A1A2E')
        .text('🎒 Packing Tips');
      doc.moveDown(0.5);

      for (const tip of itinerary.packing_tips) {
        doc
          .fontSize(11)
          .font('Helvetica')
          .fillColor('#333333')
          .text(`• ${tip}`);
      }
    }

    // --- Important notes ---
    if (itinerary.important_notes && itinerary.important_notes.length > 0) {
      doc.moveDown(1.5);
      doc
        .fontSize(16)
        .font('Helvetica-Bold')
        .fillColor('#1A1A2E')
        .text('📌 Important Notes');
      doc.moveDown(0.5);

      for (const note of itinerary.important_notes) {
        doc
          .fontSize(11)
          .font('Helvetica')
          .fillColor('#333333')
          .text(`• ${note}`);
      }
    }

    doc.end();
  });
}

function renderDay(doc: InstanceType<typeof PDFDocument>, day: DayPlan): void {
  // Day header
  doc
    .fontSize(16)
    .font('Helvetica-Bold')
    .fillColor('#1A1A2E')
    .text(`Day ${day.day_number} — ${formatDate(day.date)}${day.theme ? `: ${day.theme}` : ''}`);

  doc.moveDown(0.3);

  // Items
  for (const item of day.items) {
    const emoji = typeEmoji(item.type);
    const priceStr = item.price ? ` · ${item.price.currency} ${item.price.amount}` : '';
    const ratingStr = item.rating ? ` · ⭐ ${item.rating}` : '';

    doc
      .fontSize(11)
      .font('Helvetica-Bold')
      .fillColor('#333333')
      .text(`${emoji} ${item.time}  ${item.name}${priceStr}${ratingStr}`, { continued: false });

    if (item.description) {
      doc
        .fontSize(10)
        .font('Helvetica')
        .fillColor('#666666')
        .text(`    ${item.description}`);
    }

    if (item.booking_url) {
      doc
        .fontSize(9)
        .fillColor('#2563EB')
        .text(`    → Book: ${item.booking_url}`, { link: item.booking_url });
    }

    doc.moveDown(0.2);
  }

  // Accommodation
  if (day.accommodation) {
    const checkLabel = day.accommodation.check_in ? 'Check in' : day.accommodation.check_out ? 'Check out' : 'Staying';
    doc
      .fontSize(11)
      .font('Helvetica-BoldOblique')
      .fillColor('#16A34A')
      .text(`🏨 ${checkLabel}: ${day.accommodation.name}`);

    if (day.accommodation.confirmation) {
      doc
        .fontSize(10)
        .font('Helvetica')
        .fillColor('#666666')
        .text(`   Confirmation: ${day.accommodation.confirmation}`);
    }
  }

  // Day total
  if (day.day_total) {
    doc
      .fontSize(10)
      .font('Helvetica-Bold')
      .fillColor('#666666')
      .text(`Est. Day Total: ${day.day_total.currency} ${day.day_total.amount}`);
  }

  doc.moveDown(1);

  // Page break if near bottom
  if (doc.y > 700) {
    doc.addPage();
  }
}

function typeEmoji(type: string): string {
  const map: Record<string, string> = {
    flight: '✈️', hotel: '🏨', experience: '🎭',
    restaurant: '🍽️', transport: '🚕', free_time: '🌴',
  };
  return map[type] ?? '📌';
}

function formatDate(iso: string): string {
  const d = new Date(iso);
  if (isNaN(d.getTime())) return iso;
  return d.toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' });
}
